name: Integration Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9.6"
  UV_VERSION: "0.7.4"

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9.6", "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install -r requirements-dev.txt

      - name: Run integration tests
        run: |
          uv run pytest tests/integration/ -v \
            --cov=create_project \
            --cov-report=term-missing \
            --cov-report=xml \
            --junit-xml=test-results/integration-${{ matrix.os }}-${{ matrix.python-version }}.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: test-results/

      - name: Upload coverage reports
        if: matrix.python-version == env.PYTHON_VERSION && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: integration
          name: integration-tests

  integration-test-summary:
    needs: integration-tests
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: integration-test-results-*
          merge-multiple: true

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "*.xml"
          check_name: Integration Test Results
          comment_mode: always